<template>
  <header
    class="
      sticky
      top-0
      z-50
      flex
      justify-between
      items-center
      space-x-1
      border-b
      bg-white
      p-4
      shadow-md
      md:px-6
    "
  >
    <NuxtLink to="/" class="text-3xl font-mono"> cartrader </NuxtLink>
  </header>
</template>